name: Docker Image CI to GCP

on:
  push:
    branches: ["master"]

jobs:
  deploy:
    name: Setup GCloud Account
    runs-on: ubuntu-latest
    environment: gcp-prod
    env:
      IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT_ID }}/site:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          service_account_key: "${{ secrets.GCP_CREDENTIALS }}"
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Config Docker
        run: gcloud auth configure-docker --quiet

      - name: Build Docker Image
        run: docker build -t $IMAGE_NAME .

      - name: Push Docker Image
        run: docker push $IMAGE_NAME

      - name: Deploy Docker Image
        run: gcloud run deploy site --image $IMAGE_NAME --region us-central --memory 128Mi --min-instances 0 --max-instances 1 --platform managed --port 80 --allow-unauthenticated
